[package]
name = "uni-bachelor-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Aarón Flores Alberca <@bxcowo>", "Alejandro Cobos <@Cobos-Bioinfo>"]
license = "MIT"
description = "Tesis de pregrado de la Universidad Nacional de Ingeniería."
repository = "https://github.com/bxcowo/uni-bachelor-thesis"
keywords = ["thesis", "tesis", "pregrado", "universidad nacional de ingeniería", "uni"]
categories = ["thesis", "report"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
